LocalSocket /var/run/clamav/clamd.ctl
TCPSocket 3310
TCPAddr 127.0.0.1
LogFile /var/log/clamav/clamav.log
LogTime yes
DatabaseDirectory /var/lib/clamav
OnAccessMountPath /home
OnAccessMountPath /tmp
OnAccessPrevention no
OnAccessExtraScanning no
ScanPDF yes
ScanHTML yes
MaxFileSize 25M
MaxScanSize 100M