weekly
rotate 1
create
dateext
compress

/var/log/syslog {
    daily
    rotate 1
    compress
    missingok
    notifempty
}

/var/log/nginx/*.log {
    monthly
    rotate 1
    compress
    delaycompress
    sharedscripts
}